import React from 'react'

const Availablity = () => {
  return (
    <div className="gray-bg padding ptb-xs-40">
			<div className="container">
				<div className="row pb-30 text-center">
					<div className="col-sm-12 mb-20">
						<h2>Investment Plans of the Company</h2>
						
					</div>
				</div>
				<div className="row">
					<div className="col-sm-4">
						<div className="text__block dark-color">
							<div className="about__block-box">
								<div className='topIconContainer'>
								<div className="service_icon1">
									<img src='assets/images/tokenizaiton.png' className='value_proposition'/>
									

								</div>
								<div className="service_details1">
									<h3>
									Introduction to Tokenization
</h3>
								</div>
								</div>
								<div className="service_content">
									<p>
									Our company plans to introduce tokens that represent company shares. 
									Each individual purchasing these tokens becomes a participant in the profits generated by the company. 
									50% of all company shares will be reflected through tokens,
									 and their market quantity will be adjusted as needed.
									</p>
								</div>
							</div>
						</div>
					</div>
					<div className="col-sm-4">
						<div className="text__block dark-color">
							<div className="about__block-box">
							<div className='topIconContainer'>
								<div className="service_icon1">
								<img src='assets/images/technological.png' className='value_proposition'/>
									
								</div>
								<div className="service_details1">
									<h3>Technological Infrastructure</h3>
								</div>
								</div>
								<div className="service_content">
									<p>
									In the initial phase, we will launch a website with a wallet, 
									and our tokens will be listed on platforms such as CoinMarketCap and CoinGecko. Additionally,
									 we will create our own wallet on our website, enabling storage, 
									value tracking, and profit generation from held tokens.</p>
								</div>
							</div>
						</div>
					</div>
					<div className="col-sm-4">
						<div className="text__block dark-color">
							<div className="about__block-box">
							<div className='topIconContainer'>
								<div className="service_icon1">
								<img src='assets/images/development_fund.png' className='value_proposition'/>
									
							
								</div>
								<div className="service_details1">
									<h3>Development <br/> Funding
</h3>
								</div>
								</div>
								<div className="service_content">
									<p>
									All proceeds from token sales will be allocated to platform development and the purchase of assets on which subsequent projects will be based.
									 Our tokens differ from standard stablecoins, 
									as their value will increase with the associated asset, making investments more attractive.
									</p>
								</div>
							</div>
						</div>
					</div>


					<div className="col-sm-4">
						<div className="text__block dark-color">
							<div className="about__block-box">
							<div className='topIconContainer'>
								<div className="service_icon1">
								<img src='assets/images/assetsinvestment.png' className='value_proposition'/>
									
								</div>
								<div className="service_details1">
									<h3>Investments<br/>
										 in Assets

</h3>
								</div>
								</div>
								<div className="service_content">
									<p>
									
									Managing the acquired funds, the company plans to invest in diverse income-generating assets.
									 Assets will be available for purchase through tokenization,
									 allowing investors to participate in real estate, lands, hotels, and other projects.


									</p>
								</div>
							</div>
						</div>
					</div>


					<div className="col-sm-4">
						<div className="text__block dark-color">
							<div className="about__block-box">
							<div className='topIconContainer'>
								<div className="service_icon1">
								<img src='assets/images/assettokenization.png' className='value_proposition'/>
								</div>
								<div className="service_details1">
									<h3>Asset Tokenization

</h3>
								</div>
								</div>
								<div className="service_content">
									<p>
									
									Our platform will enable the tokenization of assets,
									 allowing users to acquire shares in various investments. Tokens,
									  such as "Real Golds," will be used to pay commissions from the profits earned by the company and will be available on our platform.


									</p>
								</div>
							</div>
						</div>
					</div>


					<div className="col-sm-4">
						<div className="text__block dark-color">
							<div className="about__block-box">
							<div className='topIconContainer'>
								<div className="service_icon1">
								<img src='assets/images/communitygroup.png' className='value_proposition'/>	
									
								</div>
								<div className="service_details1">
									<h3>Community Decisions and Investment

</h3>
								</div>
								</div>
								<div className="service_content">
									<p>
									
									We are building a community that can propose asset tokenization and vote on decisions related to a particular asset (sale, rental, etc.). 
									Our company will manage tokenization, the sale of tokens associated with a specific asset,
									 and profits will be evenly distributed among token holders.


									</p>
								</div>
							</div>
						</div>
					</div>

					<div className="col-sm-4">
						<div className="text__block dark-color">
							<div className="about__block-box">
								<div className="service_icon1">
									<i className="hi-icon fa fa-file-text-o"></i>
								</div>
								<div className="service_details1">
									<h3>Real Invest Company


</h3>
								</div>
								<div className="service_content">
									<p>
									
									Real Invest Company aims to acquire and manage existing companies using tokenization. 
									Investment terms will determine the percentage share in profits, 
									with no restrictions on the type of assets.


									</p>
								</div>
							</div>
						</div>
					</div>


					<div className="col-sm-4">
						<div className="text__block dark-color">
							<div className="about__block-box">
							<div className='topIconContainer'>
								<div className="service_icon1">
								<img src='assets/images/expantion.png' className='value_proposition'/>	
									
								</div>
								<div className="service_details1">
									<h3>International Expansion



</h3>
								</div>
								</div>
								<div className="service_content">
									<p>
									
									Over time, we plan to expand into international markets by establishing branches in different countries.



									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
  )
}

export default Availablity