import React,{useEffect} from 'react'
import { Image, Box, Link,chakra,Flex,SimpleGrid} from '@chakra-ui/react'

import AOS from 'aos';
import 'aos/dist/aos.css';
const Availablity = () => {

	useEffect(() =>{
		AOS.init({duration: 1000})
		
		},[])

  return (
    <div className="gray-bg padding ptb-xs-40">
			<div className="container">
				<div className="row pb-30 text-center" >
					<div className="col-sm-12 mb-20">
						<h2>Investment Plans of the Company</h2>
						
					</div>
				</div>
				<div className="row">
			
        <section class="work padding-top padding-bottom bg--primary-color">
        <div class="container">
            <div class="section-header section-header--middle">
                <div class="section-header__content">
                    <div class="section-header__titlebar">
                      
                      
                    </div>
                </div>
            </div>
            <div class="work__wrapper">
                <div class="row  justify-content-center g-4">
                   
                    
                    <div class="col-lg-4 col-sm-6">
                        <div class="work__item">
                            <div class="work__item-inner">
                                <div class="work__item-thumb">
                                    <img   src='assets/images/icon_new1.png' alt="work Step 3 Image"/>
                                </div>
                                <div class="work__item-content">
                                    <h4> Introduction to Tokenization</h4>
                                    <p>Our company plans to introduce tokens that represent company shares. 
      Each individual purchasing these tokens becomes a participant in the profits generated by the company.
       50% of all company shares will be reflected through tokens, 
      and their market quantity will be adjusted as needed.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="work__item">
                            <div class="work__item-inner">
                                <div class="work__item-thumb">
                                    <img src='assets/images/icon_new3.png' alt="work Step 2 Image"/>
                                </div>
                                <div class="work__item-content">
                                    <h4>Technological Infrastructure</h4>
                                    <p>In the initial phase, we will launch a website with a wallet, 
                                      and our tokens will be listed on platforms such as CoinMarketCap and CoinGecko. 
                                      Additionally, we will create our own wallet on our website, 
                                      enabling storage, value tracking, and profit generation from held tokens.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-sm-6">
                        <div class="work__item">
                            <div class="work__item-inner">
                                <div class="work__item-thumb">
                                    <img src="assets/images/icon_new2.png" alt="work Step 1 Image"/>
                                </div>
                                <div class="work__item-content">
                                    <h4>Development Funding</h4>
                                    <p>All proceeds from token sales will be allocated to platform development 
                                      and the purchase of assets on which subsequent projects will be based.
                                       Our tokens differ from standard stablecoins, as their value will increase with the associated asset,
                                       making investments more attractive.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-sm-6">
                        <div class="work__item">
                            <div class="work__item-inner">
                                <div class="work__item-thumb">
                                    <img src="assets/images/new_icon4.png" alt="work Step 1 Image"/>
                                </div>
                                <div class="work__item-content">
                                    <h4>Investments In Assets</h4>
                                    <p>Managing the acquired funds, the company plans to invest in diverse income-generating assets.
                                       Assets will be available for purchase through tokenization, allowing investors to participate in real estate,
                                       lands, hotels, and other projects.</p>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-4 col-sm-6">
                        <div class="work__item">
                            <div class="work__item-inner">
                                <div class="work__item-thumb">
                                    <img src="assets/images/icon_new5.png" alt="work Step 1 Image"/>
                                </div>
                                <div class="work__item-content">
                                    <h4>Asset Tokenization</h4>
                                    <p>Our platform will enable the tokenization of assets,
                                       allowing users to acquire shares in various investments. 
                                       Tokens, such as "Real Golds," 
                                       will be used to pay commissions from the profits earned by the company and will be available on our platform.</p>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-4 col-sm-6">
                        <div class="work__item">
                            <div class="work__item-inner">
                                <div class="work__item-thumb">
                                    <img src="assets/images/icon_new71.png" alt="work Step 1 Image"/>
                                </div>
                                <div class="work__item-content">
                                    <h4>Community Decisions And Investment</h4>
                                    <p>We are building a community that can propose asset tokenization and vote
                                       on decisions related to a particular asset (sale, rental, etc.). 
                                       Our company will manage tokenization,
                                       the sale of tokens associated with a specific asset, 
                                       and profits will be evenly distributed among token holders.</p>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-4 col-sm-6">
                        <div class="work__item">
                            <div class="work__item-inner">
                                <div class="work__item-thumb">
                                    <img src="assets/images/new_icon7.png" alt="work Step 1 Image"/>
                                </div>
                                <div class="work__item-content">
                                    <h4>International Expansion</h4>
                                    <p>Over time, we plan to expand into international markets by establishing branches in different countries.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </section>
{/* <SimpleGrid columns={3}  py={6} ml={10}
           minChildWidth="250px"
           spacing={20}
           flexWrap="wrap"
           
           
            
>
  <Box
    w="350px"
    mx="auto"
    
    py={4}
    px={8}
    bg="white"
    _dark={{
      bg: "gray.800",
    }}
    shadow="lg"
    rounded="lg"
  >
    <Flex
      justifyContent={{
        base: "center",
        md: "end",
      }}
      mt={-16}
    >
      <Image
        w={20}
        h={20}
        fit="cover"
        justifySelf="center"
        ml="20px"
        rounded="full"
        borderStyle="solid"
        borderWidth={2}
        color="#d86b34"
        _dark={{
          color: "brand.400",
        }}
        alt="Testimonial avatar"
        src='assets/images/icon3.png'
      />
    </Flex>

    <chakra.h2
      color="gray.800"
      _dark={{
        color: "white",
      }}
      fontSize={{
        base: "2xl",
        md: "3xl",
      }}
      textAlign={'left'}
      alignItems="center"
      mt={{
        md: 0,
      }}
      fontWeight="bold"
    >
      Introduction to Tokenization

    </chakra.h2>

    <chakra.p
      mt={2}
      color="gray.600"
      _dark={{
        color: "gray.200",
      }}
    >
    	Our company plans to introduce tokens that represent company shares. 
      Each individual purchasing these tokens becomes a participant in the profits generated by the company.
       50% of all company shares will be reflected through tokens, 
      and their market quantity will be adjusted as needed.
    </chakra.p>

    
  </Box>

  <Box
    w="350px"
    mx="auto"
    py={4}
    px={8}
    bg="white"
    _dark={{
      bg: "gray.800",
    }}
    shadow="lg"
    rounded="lg"
  >
    <Flex
      justifyContent={{
        base: "center",
        md: "end",
      }}
      mt={-16}
    >
      <Image
        w={20}
        h={20}
        fit="cover"
        position="center"
        ml={20}
        rounded="full"
        borderStyle="solid"
        borderWidth={2}
        color="#d86b34"
        _dark={{
          color: "brand.400",
        }}
        alt="Testimonial avatar"
      	src='assets/images/icon5.png'
      />
    </Flex>

    <chakra.h2
      color="gray.800"
      _dark={{
        color: "white",
      }}
      fontSize={{
        base: "2xl",
        md: "3xl",
      }}
      textAlign={'left'}
      alignItems="center"
      mt={{
        md: 0,
      }}
      fontWeight="bold"
    >
      Technological Infrastructure

    </chakra.h2>

    <chakra.p
      mt={2}
      color="gray.600"
      _dark={{
        color: "gray.200",
      }}
    >
    	In the initial phase, we will launch a website with a wallet,
       and our tokens will be listed on platforms such as CoinMarketCap and CoinGecko. Additionally,
        we will create our own wallet on our website, enabling storage, value tracking,
       and profit generation from held tokens.
    </chakra.p>

    
  </Box>
  <Box
    w="350px"
    mx="auto"
    py={4}
    px={8}
    bg="white"
    _dark={{
      bg: "gray.800",
    }}
    shadow="lg"
    rounded="lg"
  >
    <Flex
      justifyContent={{
        base: "center",
        md: "end",
      }}
      mt={-16}
    >
      <Image
        w={20}
        h={20}
        fit="cover"
        position="center"
        ml={20}
        rounded="full"
        borderStyle="solid"
        borderWidth={2}
        color="#d86b34"
        _dark={{
          color: "brand.400",
        }}
        alt="Testimonial avatar"
        src='assets/images/icon2.png' 
      />
    </Flex>

    <chakra.h2
      color="gray.800"
      _dark={{
        color: "white",
      }}
      fontSize={{
        base: "2xl",
        md: "3xl",
      }}
      textAlign={'left'}
      alignItems="center"
      mt={{
        md: 0,
      }}
      fontWeight="bold"
    >
      Development Funding

    </chakra.h2>

    <chakra.p
      mt={2}
      color="gray.600"
      _dark={{
        color: "gray.200",
      }}
    >
    
All proceeds from token sales will be allocated to platform development and the purchase of assets on which subsequent projects will be based. 
Our tokens differ from standard stablecoins, as their value will increase with the associated asset, making investments more attractive.

    </chakra.p>

    
  </Box>

  <Box
     w="350px"
    mx="auto"
    py={4}
    px={8}
    bg="white"
    _dark={{
      bg: "gray.800",
    }}
    shadow="lg"
    rounded="lg"
  >
    <Flex
      justifyContent={{
        base: "center",
        md: "end",
      }}
      mt={-16}
    >
      <Image
        w={20}
        h={20}
        fit="cover"
        alignItems="center"
        rounded="full"
        borderStyle="solid"
        bg="white"
        borderWidth={2}
        color="#d86b34"
        _dark={{
          color: "brand.400",
        }}
        alt="Testimonial avatar"
        src='assets/images/icon1.png'
      />
    </Flex>

    <chakra.h2
      color="gray.800"
      _dark={{
        color: "white",
      }}
      fontSize={{
        base: "2xl",
        md: "3xl",
      }}
      textAlign={'left'}
     
      
      fontWeight="bold"
    >
    Investments in Assets
    </chakra.h2>

    <chakra.p
      mt={2}
      color="gray.600"
      _dark={{
        color: "gray.200",
      }}
    >
    	Managing the acquired funds, the company plans to invest in diverse income-generating assets.
       Assets will be available for purchase through tokenization, allowing investors to participate in real estate, lands,
        hotels, and other projects.

    </chakra.p>

    
  </Box>

  <Box
     w="350px"
    mx="auto"
    py={4}
    px={8}
    bg="white"
    _dark={{
      bg: "gray.800",
    }}
    shadow="lg"
    rounded="lg"
  >
    <Flex
      justifyContent={{
        base: "center",
        md: "end",
      }}
      mt={-16}
    >
      <Image
        w={20}
        h={20}
        fit="contain"
        alignItems="center"
        rounded="full"
        borderStyle="solid"
        bg="white"
        borderWidth={2}
        color="#d86b34"
        _dark={{
          color: "brand.400",
        }}
        alt="Testimonial avatar"
        src='assets/images/icon8.png'
      />
    </Flex>

    <chakra.h2
      color="gray.800"
      _dark={{
        color: "white",
      }}
      fontSize={{
        base: "2xl",
        md: "3xl",
      }}
      textAlign={'left'}
     
      
      fontWeight="bold"
    >
Asset Tokenization

    </chakra.h2>

    <chakra.p
      mt={2}
      color="gray.600"
      _dark={{
        color: "gray.200",
      }}
    >
    	Our platform will enable the tokenization of assets, allowing users to acquire shares in various investments. Tokens, 
      such as "Real Golds," will be used to pay commissions from the profits earned by the company and will be available on our platform.

    </chakra.p>

    
  </Box>


  <Box
     w="350px"
    mx="auto"
    py={4}
    px={8}
    bg="white"
    _dark={{
      bg: "gray.800",
    }}
    shadow="lg"
    rounded="lg"
  >
    <Flex
      justifyContent={{
        base: "center",
        md: "end",
      }}
      mt={-16}
    >
      <Image
        w={20}
        h={20}
        fit="contain"
        alignItems="center"
        rounded="full"
        borderStyle="solid"
        bg="white"
        borderWidth={2}
        color="#d86b34"
        _dark={{
          color: "brand.400",
        }}
        alt="Testimonial avatar"
        src='assets/images/icon7.png'
      />
    </Flex>

    <chakra.h2
      color="gray.800"
      _dark={{
        color: "white",
      }}
      fontSize={{
        base: "2xl",
        md: "3xl",
      }}
      textAlign={'left'}
     
      
      fontWeight="bold"
    >
    Community Decisions and Investment 
    </chakra.h2>

    <chakra.p
      mt={2}
      color="gray.600"
      _dark={{
        color: "gray.200",
      }}
    >
    
We are building a community that can propose asset tokenization and vote on decisions related to a particular asset (sale, rental, etc.).
 Our company will manage tokenization, the sale of tokens associated with a specific asset,
  and profits will be evenly distributed among token holders.


    </chakra.p>

    
  </Box>

  <Box
     w="350px"
    height="210px"
    mx="auto"
    py={4}
    px={8}
    bg="white"
    _dark={{
      bg: "gray.800",
    }}
    shadow="lg"
    rounded="lg"
  >
    <Flex
      justifyContent={{
        base: "center",
        md: "end",
      }}
      mt={-16}
    >
      <Image
        w={20}
        h={20}
        fit="contain"
        alignItems="center"
        rounded="full"
        borderStyle="solid"
        bg="white"
        borderWidth={2}
        color="#d86b34"
        _dark={{
          color: "brand.400",
        }}
        alt="Testimonial avatar"
        src='assets/images/icon.png' 
      />
    </Flex>

    <chakra.h2
      color="gray.800"
      _dark={{
        color: "white",
      }}
      fontSize={{
        base: "2xl",
        md: "3xl",
      }}
      textAlign={'left'}
     
      
      fontWeight="bold"
    >
    International Expansion
    </chakra.h2>

    <chakra.p
      mt={2}
      color="gray.600"
      _dark={{
        color: "gray.200",
      }}
    >
Over time, we plan to expand into international markets by establishing branches in different countries.



    </chakra.p>

    
  </Box>
</SimpleGrid>; */}

				</div>
			</div>
		</div>
  )
}

export default Availablity